// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_PHE.Data;

#nullable disable

namespace Project_PHE.Migrations
{
    [DbContext(typeof(PheDbContext))]
    [Migration("20231230041812_DbCOntext")]
    partial class DbCOntext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.Property<string>("EmployeeRolesGuid")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("RoleEmployesGuid")
                        .HasColumnType("varchar(36)");

                    b.HasKey("EmployeeRolesGuid", "RoleEmployesGuid");

                    b.HasIndex("RoleEmployesGuid");

                    b.ToTable("EmployeeRole");
                });

            modelBuilder.Entity("Project_PHE.Entities.Approvel", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("guid");

                    b.Property<string>("ApprovalVendor")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("vendor");

                    b.HasKey("Guid")
                        .HasName("PRIMARY");

                    b.ToTable("approvel", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Project_PHE.Entities.Employee", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("guid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("phone");

                    b.Property<string>("RoleEmployee")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Guid")
                        .HasName("PRIMARY");

                    b.ToTable("employee", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Project_PHE.Entities.Role", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("guid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Guid")
                        .HasName("PRIMARY");

                    b.ToTable("role", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");

                    b.HasData(
                        new
                        {
                            Guid = "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                            Name = "user"
                        },
                        new
                        {
                            Guid = "6f0cab9c-77ee-4720-fbe7-08db584bbbc0",
                            Name = "admin"
                        },
                        new
                        {
                            Guid = "158f7caf-D2AD-45ad-4c30-08db58db1641",
                            Name = "manager"
                        },
                        new
                        {
                            Guid = "158f7caf-D2AD-45ad-4c30-48db58db1641",
                            Name = "vendor"
                        });
                });

            modelBuilder.Entity("Project_PHE.Entities.Vendor", b =>
                {
                    b.Property<string>("Guid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("guid");

                    b.Property<string>("EmailCompany")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_company");

                    b.Property<string>("EmployeeVendor")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("IsApproved")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("is_approved");

                    b.Property<string>("NameCompany")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name_company");

                    b.Property<string>("PhoneCompany")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("phone_company");

                    b.Property<byte[]>("UploadImage")
                        .HasMaxLength(255)
                        .HasColumnType("varbinary(255)")
                        .HasColumnName("upload_image");

                    b.HasKey("Guid")
                        .HasName("PRIMARY");

                    b.HasIndex("EmployeeVendor")
                        .IsUnique();

                    b.ToTable("vendor", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("EmployeeRole", b =>
                {
                    b.HasOne("Project_PHE.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeRolesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_PHE.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleEmployesGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Project_PHE.Entities.Approvel", b =>
                {
                    b.HasOne("Project_PHE.Entities.Vendor", "VendorNavigation")
                        .WithOne("ApprovelNavigation")
                        .HasForeignKey("Project_PHE.Entities.Approvel", "Guid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VendorNavigation");
                });

            modelBuilder.Entity("Project_PHE.Entities.Vendor", b =>
                {
                    b.HasOne("Project_PHE.Entities.Employee", "EmployeeNavigation")
                        .WithOne("VendorNavigation")
                        .HasForeignKey("Project_PHE.Entities.Vendor", "EmployeeVendor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeNavigation");
                });

            modelBuilder.Entity("Project_PHE.Entities.Employee", b =>
                {
                    b.Navigation("VendorNavigation")
                        .IsRequired();
                });

            modelBuilder.Entity("Project_PHE.Entities.Vendor", b =>
                {
                    b.Navigation("ApprovelNavigation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
